[package]
name = 'bash-semver'
slug = 'bash_semver'
version = '0.2.2'
authors = ['Edwin Kofler <edwin@kofler.dev>']
description = 'Semantic Versioning for Bash'

[run]
dependencies = ['https://github.com/hyperupcall/bats-common-utils.git@v3.0.0']
sourceDirs = ['pkg/lib/public']
builtinDirs = []
binDirs = []
completionDirs = []
manDirs = []

[run.shellEnvironment]

[run.setOptions]

[run.shoptOptions]
